# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jisung's Blog
tagline:             'Machine Learning & Deep Learning'
description:         'Welcome to Jisung\'s Blog. I post random Machine Learning topics. My github is [here](https://github.com/niffler92)'
url:                 https://niffler92.github.io
baseurl:             ''
paginate:            3
paginate_path:       "page:num"
future:              true

# About/contact
author:
  name:              Jisung Hwang
  url:               https://github.com/niffler92
  email:             jeshwang92@gmail.com

# Custom vars
version:             1.0.0
